config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :tasks
  end
  
  root 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :tasks, dependent: :destroy 
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		@project = Project.all
	end
	def new
		@project = Project.new
	end
	def create
		@project = Project.create(project_params)
		redirect_to projects_path
	end
	def edit
		@project = Project.find(params[:id])
	end
	def update
		@project = Project.find(params[:id])
		@project.update(project_params)
		redirect_to @project
	end

	def show
		@project = Project.find(params[:id])
	end

	def destroy
		@project = Project.find(params[:id])
		@project.destroy
		redirect_to projects_path
	end



	# STRONG PARAMETERS
	private
		def project_params
			params.require(:project).permit(:name)
		end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	def create
		@project = Project.find(params[:project_id])
		@task = @project.tasks.create(tasks_params)
		redirect_to project_path(@project)
	end

	def new 
		@project = Project.find(params[:project_id])
	end
	def show
		@project = Project.find(params[:project_id])
		@task = @project.tasks.find(params[:id])
	end

	def destroy
		@project = Project.find(params[:project_id])
		@task = @project.tasks.find(params[:id])
		@task.destroy
		redirect_to project_path(@project)
	end

	private
	def tasks_params
		params.require(:task).permit(:name,:due_date,:status,:priority)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kanbanz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%=form_for @project do |f| %>
	Project's name: <%= f.text_field :name%><br>
	<%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<%= render 'form' %>
<%= link_to 'Back to project', project_path(@project) %>

app/views/projects/index.html.erb
<p>
	<h1>Projects Listing</h1> / <%= link_to 'Create New Project', new_project_path %>
</p>

<% @project.each do |f| %>
	<p>
		<h2>
			<%= link_to f.name, project_path(f) %>
		</h2>
	</p>
<%end%>

app/views/projects/new.html.erb
<%= render 'form' %><br>
<%= link_to 'Back to listing', projects_path %>

app/views/projects/show.html.erb
<h1>
	PROJECT: <%= @project.name %> / <%=link_to 'Edit', edit_project_path(@project) 
	%>
</h1>	
<h2> Tasks within this project</h2><br>
<%= link_to "Create a new task", new_project_task_path(@project) %>
<p>

<% @project.tasks.each do |f| %>	
		<%= link_to f.name, project_task_path(@project,f) %> / 
		<%= link_to 'Destroy task', project_task_path(@project,f), method: :delete, data:{ confirm: "Are you sure?"} %><br>
<% end %>

</p>

<%= link_to 'Back to listing', projects_path %> <br>
<%= link_to 'Destroy Project', project_path(@project), method: :delete, data: {confirm: "Are you sure?"} %>

app/views/tasks/_form.html.erb
<%= form_for ([@project, @project.tasks.build])  do |f| %>
	Task name: <%= f.text_field :name %><br>
	Priority: <%= f.text_field :priority %><br>
	Status: <%= f.text_field :status %><br>
	Due date: <%= f.text_field :due_date %><br><br>
	<%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form'%>
<%= link_to "Back to listing", tasks_path%>	

app/views/tasks/index.html.erb
Listing tasks | <%= link_to "New task" ,new_task_path %>

<% @tasks.each do |f| %>
	<p><h1><%= link_to f.name, task_path(f)%> | <%=link_to 'Edit', edit_task_path(f)%></h1><br>
	ID: <%= f.id %><br>
	STATUS: <%= f.status %><br>
	DUE DATE: <%= f.due_date %><br>
	PRIORIRY: <%= f.priority %><br>
	CREATED AT: <%= f.created_at %><br>
	UPDATED AT: <%= f.updated_at %><br>
	<%= link_to 'Destroy task', task_path(f), method: :delete, data: {confirm: "Are you sure?"} %>
	<hr></p>
<% end %>

app/views/tasks/new.html.erb
<h1> New task</h1>
<%= render 'form'%>
	

app/views/tasks/show.html.erb
<h1><%= @task.name %></h1>
due date:<%= @task.due_date %><br>
priority: <%= @task.priority %><br>
status: <%= @task.status %><br>
created at: <%= @task.created_at %><br>
updated at: <%= @task.updated_at %><br>
<br>
<%= link_to 'Back to listing', project_path(@project) %>